name: ci-golang
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    strategy:
      matrix:
        go: ["1.17", "1.18"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go